<?php return [
  'models' => [
    'emails' => false,
    'failed_jobs' => false,
    'migrations' => false,
    'password_resets' => false,
    'settings' => false,
    'temtrem_businesses' => true,
    'temtrem_products' => true,
    'users' => true,
    'users_notifications' => false,
    'temtrem_business' => true,
  ],
  'controllers' => [
    'emails' => false,
    'failed_jobs' => false,
    'migrations' => false,
    'password_resets' => false,
    'settings' => false,
    'temtrem_businesses' => true,
    'temtrem_products' => true,
    'users' => true,
    'users_notifications' => false,
    'temtrem_business' => true,
  ],
];