<?php return [
  'tables' => [
    'email_sents' => [
      'pk' => 'id',
      'field_label' => 'id',
      'field_image' => false,
      'singular' => 'Email_sent',
      'plural' => 'Email_sents',
      'in_nav' => false,
      'model' => false,
      'icon' => 'fas fa-globe',
      'route' => 'email-sent',
      'fields' => [
        'id' => [
          'field' => 'id',
          'label' => 'ID',
          'input_type' => false,
          'input_bind' => false,
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => false,
        ],
        'to' => [
          'field' => 'to',
          'label' => 'To',
          'input_type' => 'ui-text',
          'input_bind' => [
            'multiline' => 'true',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'subject' => [
          'field' => 'subject',
          'label' => 'Subject',
          'input_type' => 'ui-text',
          'input_bind' => [
            'multiline' => 'true',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'body' => [
          'field' => 'body',
          'label' => 'Body',
          'input_type' => 'ui-text',
          'input_bind' => [
            'multiline' => 'true',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'created_at' => [
          'field' => 'created_at',
          'label' => 'Criado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'updated_at' => [
          'field' => 'updated_at',
          'label' => 'Alterado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
      ],
    ],
    'emails' => [
      'pk' => 'id',
      'field_label' => 'name',
      'field_image' => false,
      'singular' => 'Email',
      'plural' => 'Emails',
      'in_nav' => true,
      'model' => true,
      'icon' => 'fas fa-globe',
      'route' => 'email',
      'fields' => [
        'id' => [
          'field' => 'id',
          'label' => 'ID',
          'input_type' => false,
          'input_bind' => false,
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => false,
        ],
        'name' => [
          'field' => 'name',
          'label' => 'Name',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'subject' => [
          'field' => 'subject',
          'label' => 'Subject',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'body' => [
          'field' => 'body',
          'label' => 'Body',
          'input_type' => 'ui-text',
          'input_bind' => [
            'multiline' => 'true',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'params' => [
          'field' => 'params',
          'label' => 'Params',
          'input_type' => 'ui-text',
          'input_bind' => [
            'multiline' => 'true',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'created_at' => [
          'field' => 'created_at',
          'label' => 'Criado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'updated_at' => [
          'field' => 'updated_at',
          'label' => 'Alterado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
      ],
    ],
    'migrations' => [
      'pk' => 'id',
      'field_label' => 'migration',
      'field_image' => false,
      'singular' => 'Migration',
      'plural' => 'Migrations',
      'in_nav' => false,
      'model' => false,
      'icon' => 'fas fa-globe',
      'route' => 'migration',
      'fields' => [
        'id' => [
          'field' => 'id',
          'label' => 'ID',
          'input_type' => false,
          'input_bind' => false,
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => false,
        ],
        'migration' => [
          'field' => 'migration',
          'label' => 'Migration',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'batch' => [
          'field' => 'batch',
          'label' => 'Batch',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
      ],
    ],
    'password_resets' => [
      'pk' => false,
      'field_label' => 'email',
      'field_image' => false,
      'singular' => 'Password_reset',
      'plural' => 'Password_resets',
      'in_nav' => false,
      'model' => false,
      'icon' => 'fas fa-globe',
      'route' => 'password-reset',
      'fields' => [
        'email' => [
          'field' => 'email',
          'label' => 'Email',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'token' => [
          'field' => 'token',
          'label' => 'Token',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'created_at' => [
          'field' => 'created_at',
          'label' => 'Criado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'updated_at' => [
          'field' => 'updated_at',
          'label' => 'Alterado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
      ],
    ],
    'settings' => [
      'pk' => 'id',
      'field_label' => 'name',
      'field_image' => false,
      'singular' => 'Setting',
      'plural' => 'Settings',
      'in_nav' => false,
      'model' => true,
      'icon' => 'fas fa-globe',
      'route' => 'setting',
      'fields' => [
        'id' => [
          'field' => 'id',
          'label' => 'ID',
          'input_type' => false,
          'input_bind' => false,
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => false,
        ],
        'name' => [
          'field' => 'name',
          'label' => 'Name',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'value' => [
          'field' => 'value',
          'label' => 'Value',
          'input_type' => 'ui-text',
          'input_bind' => [
            'multiline' => 'true',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'value_default' => [
          'field' => 'value_default',
          'label' => 'Value_default',
          'input_type' => 'ui-text',
          'input_bind' => [
            'multiline' => 'true',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'description' => [
          'field' => 'description',
          'label' => 'Description',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'help' => [
          'field' => 'help',
          'label' => 'Help',
          'input_type' => 'ui-text',
          'input_bind' => [
            'multiline' => 'true',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
      ],
    ],
    'temtrem_businesses' => [
      'pk' => 'id',
      'field_label' => 'name',
      'field_image' => false,
      'singular' => 'Negócio',
      'plural' => 'Negócios',
      'in_nav' => true,
      'model' => true,
      'icon' => 'fas fa-globe',
      'route' => 'temtrem-business',
      'fields' => [
        'id' => [
          'field' => 'id',
          'label' => 'ID',
          'input_type' => false,
          'input_bind' => false,
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => false,
        ],
        'user_id' => [
          'field' => 'user_id',
          'label' => 'User_id',
          'input_type' => 'ui-user',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'category_id' => [
          'field' => 'category_id',
          'label' => 'Categoria',
          'input_type' => 'ui-temtrem-category',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => true,
        ],
        'name' => [
          'field' => 'name',
          'label' => 'Name',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'type' => [
          'field' => 'type',
          'label' => 'Type',
          'input_type' => 'ui-temtrem-business-type',
          'input_bind' => [],
          'input_options' => [
            'store' => 'Store',
            'service' => 'Service',
          ],
          'in_datatable' => true,
          'in_form' => true,
        ],
        'nomadic' => [
          'field' => 'nomadic',
          'label' => 'Nomadic',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => true,
        ],
        'nomadic_lat' => [
          'field' => 'nomadic_lat',
          'label' => 'Nomadic_lat',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'nomadic_lng' => [
          'field' => 'nomadic_lng',
          'label' => 'Nomadic_lng',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'content' => [
          'field' => 'content',
          'label' => 'Content',
          'input_type' => 'ui-text',
          'input_bind' => [
            'multiline' => 'true',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => true,
        ],
        'lat' => [
          'field' => 'lat',
          'label' => 'Lat',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'lng' => [
          'field' => 'lng',
          'label' => 'Lng',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'route' => [
          'field' => 'route',
          'label' => 'Route',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'number' => [
          'field' => 'number',
          'label' => 'Number',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'complement' => [
          'field' => 'complement',
          'label' => 'Complement',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'zipcode' => [
          'field' => 'zipcode',
          'label' => 'Zipcode',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'district' => [
          'field' => 'district',
          'label' => 'District',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'city' => [
          'field' => 'city',
          'label' => 'City',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'state' => [
          'field' => 'state',
          'label' => 'State',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'st' => [
          'field' => 'st',
          'label' => 'St',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'country' => [
          'field' => 'country',
          'label' => 'Country',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'co' => [
          'field' => 'co',
          'label' => 'Co',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'created_at' => [
          'field' => 'created_at',
          'label' => 'Criado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'updated_at' => [
          'field' => 'updated_at',
          'label' => 'Alterado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'deleted_at' => [
          'field' => 'deleted_at',
          'label' => 'Deletado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
      ],
    ],
    'temtrem_businesses_items' => [
      'pk' => 'id',
      'field_label' => 'id',
      'field_image' => false,
      'singular' => 'Temtrem_businesses_item',
      'plural' => 'Temtrem_businesses_items',
      'in_nav' => true,
      'model' => true,
      'icon' => 'fas fa-globe',
      'route' => 'temtrem-businesses-item',
      'fields' => [
        'id' => [
          'field' => 'id',
          'label' => 'ID',
          'input_type' => false,
          'input_bind' => false,
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => false,
        ],
        'store' => [
          'field' => 'store',
          'label' => 'Store',
          'input_type' => 'ui-user',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'name' => [
          'field' => 'name',
          'label' => 'Name',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
      ],
    ],
    'temtrem_businesses_posts' => [
      'pk' => 'id',
      'field_label' => 'title',
      'field_image' => false,
      'singular' => 'Temtrem_businesses_post',
      'plural' => 'Temtrem_businesses_posts',
      'in_nav' => true,
      'model' => true,
      'icon' => 'fas fa-globe',
      'route' => 'temtrem-businesses-post',
      'fields' => [
        'id' => [
          'field' => 'id',
          'label' => 'ID',
          'input_type' => false,
          'input_bind' => false,
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => false,
        ],
        'business_id' => [
          'field' => 'business_id',
          'label' => 'Business_id',
          'input_type' => 'ui-temtrem-business',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'title' => [
          'field' => 'title',
          'label' => 'Title',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'content' => [
          'field' => 'content',
          'label' => 'Content',
          'input_type' => 'ui-text',
          'input_bind' => [
            'multiline' => 'true',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'created_at' => [
          'field' => 'created_at',
          'label' => 'Criado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'updated_at' => [
          'field' => 'updated_at',
          'label' => 'Alterado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'deleted_at' => [
          'field' => 'deleted_at',
          'label' => 'Deletado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'business' => [
          'field' => 'business',
          'label' => 'Business',
          'input_type' => 'ui-temtrem-business',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
      ],
    ],
    'temtrem_categories' => [
      'pk' => 'id',
      'field_label' => 'name',
      'field_image' => false,
      'singular' => 'Temtrem_category',
      'plural' => 'Temtrem_categories',
      'in_nav' => true,
      'model' => true,
      'icon' => 'fas fa-globe',
      'route' => 'temtrem-category',
      'fields' => [
        'id' => [
          'field' => 'id',
          'label' => 'ID',
          'input_type' => false,
          'input_bind' => false,
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => false,
        ],
        'slug' => [
          'field' => 'slug',
          'label' => 'Slug',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => true,
        ],
        'name' => [
          'field' => 'name',
          'label' => 'Name',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'icon' => [
          'field' => 'icon',
          'label' => 'Icon',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'parent' => [
          'field' => 'parent',
          'label' => 'Parent',
          'input_type' => 'ui-temtrem-category',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'created_at' => [
          'field' => 'created_at',
          'label' => 'Criado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'updated_at' => [
          'field' => 'updated_at',
          'label' => 'Alterado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'deleted_at' => [
          'field' => 'deleted_at',
          'label' => 'Deletado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
      ],
    ],
    'user_notifications' => [
      'pk' => 'id',
      'field_label' => 'title',
      'field_image' => false,
      'singular' => 'User_notification',
      'plural' => 'User_notifications',
      'in_nav' => true,
      'model' => true,
      'icon' => 'fas fa-globe',
      'route' => 'user-notification',
      'fields' => [
        'id' => [
          'field' => 'id',
          'label' => 'ID',
          'input_type' => false,
          'input_bind' => false,
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => false,
        ],
        'user_id' => [
          'field' => 'user_id',
          'label' => 'User_id',
          'input_type' => 'ui-user',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'title' => [
          'field' => 'title',
          'label' => 'Title',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'body' => [
          'field' => 'body',
          'label' => 'Body',
          'input_type' => 'ui-text',
          'input_bind' => [
            'multiline' => 'true',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'image' => [
          'field' => 'image',
          'label' => 'Image',
          'input_type' => 'ui-text',
          'input_bind' => [
            'multiline' => 'true',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'url' => [
          'field' => 'url',
          'label' => 'Url',
          'input_type' => 'ui-text',
          'input_bind' => [
            'multiline' => 'true',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'seen' => [
          'field' => 'seen',
          'label' => 'Seen',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'created_at' => [
          'field' => 'created_at',
          'label' => 'Criado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'updated_at' => [
          'field' => 'updated_at',
          'label' => 'Alterado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
      ],
    ],
    'users' => [
      'pk' => 'id',
      'field_label' => 'name',
      'field_image' => false,
      'singular' => 'Usuário',
      'plural' => 'Usuários',
      'in_nav' => true,
      'model' => true,
      'icon' => 'fas fa-globe',
      'route' => 'user',
      'fields' => [
        'id' => [
          'field' => 'id',
          'label' => 'ID',
          'input_type' => false,
          'input_bind' => false,
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => false,
        ],
        'name' => [
          'field' => 'name',
          'label' => 'Nome',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'email' => [
          'field' => 'email',
          'label' => 'E-mail',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'password' => [
          'field' => 'password',
          'label' => 'Senha',
          'input_type' => 'ui-password',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => true,
        ],
        'type' => [
          'field' => 'type',
          'label' => 'Tipo',
          'input_type' => 'ui-user-type',
          'input_bind' => [],
          'input_options' => [
            'admin' => 'Admin',
            'user' => 'User',
          ],
          'in_datatable' => true,
          'in_form' => true,
        ],
        'email_verified_at' => [
          'field' => 'email_verified_at',
          'label' => 'Email_verified_at',
          'input_type' => 'ui-text',
          'input_bind' => [
            'multiline' => 'true',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'remember_token' => [
          'field' => 'remember_token',
          'label' => 'Remember_token',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'created_at' => [
          'field' => 'created_at',
          'label' => 'Criado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'updated_at' => [
          'field' => 'updated_at',
          'label' => 'Alterado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'deleted_at' => [
          'field' => 'deleted_at',
          'label' => 'Deletado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
      ],
    ],
    'temtrem_negocios' => [
      'pk' => 'id',
      'field_label' => 'name',
      'field_image' => false,
      'singular' => 'Temtrem_negocio',
      'plural' => 'Temtrem_negocios',
      'in_nav' => true,
      'model' => true,
      'icon' => 'fas fa-globe',
      'route' => 'temtrem-negocio',
      'fields' => [
        'id' => [
          'field' => 'id',
          'label' => 'ID',
          'input_type' => false,
          'input_bind' => false,
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => false,
        ],
        'user_id' => [
          'field' => 'user_id',
          'label' => 'User_id',
          'input_type' => 'ui-user',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'name' => [
          'field' => 'name',
          'label' => 'Name',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'type' => [
          'field' => 'type',
          'label' => 'Type',
          'input_type' => 'ui-temtrem-negocio-type',
          'input_bind' => [],
          'input_options' => [
            'store' => 'Store',
            'service' => 'Service',
          ],
          'in_datatable' => true,
          'in_form' => true,
        ],
        'nomadic' => [
          'field' => 'nomadic',
          'label' => 'Nomadic',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'nomadic_lat' => [
          'field' => 'nomadic_lat',
          'label' => 'Nomadic_lat',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'nomadic_lng' => [
          'field' => 'nomadic_lng',
          'label' => 'Nomadic_lng',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'content' => [
          'field' => 'content',
          'label' => 'Content',
          'input_type' => 'ui-text',
          'input_bind' => [
            'multiline' => 'true',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'lat' => [
          'field' => 'lat',
          'label' => 'Lat',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'lng' => [
          'field' => 'lng',
          'label' => 'Lng',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'route' => [
          'field' => 'route',
          'label' => 'Route',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'number' => [
          'field' => 'number',
          'label' => 'Number',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'complement' => [
          'field' => 'complement',
          'label' => 'Complement',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'zipcode' => [
          'field' => 'zipcode',
          'label' => 'Zipcode',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'district' => [
          'field' => 'district',
          'label' => 'District',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'city' => [
          'field' => 'city',
          'label' => 'City',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'state' => [
          'field' => 'state',
          'label' => 'State',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'st' => [
          'field' => 'st',
          'label' => 'St',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'country' => [
          'field' => 'country',
          'label' => 'Country',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'co' => [
          'field' => 'co',
          'label' => 'Co',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'created_at' => [
          'field' => 'created_at',
          'label' => 'Criado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'updated_at' => [
          'field' => 'updated_at',
          'label' => 'Alterado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'deleted_at' => [
          'field' => 'deleted_at',
          'label' => 'Deletado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
      ],
    ],
    'temtrem_negocio' => [
      'pk' => 'id',
      'field_label' => 'name',
      'field_image' => false,
      'singular' => 'Temtrem_negocio',
      'plural' => 'Temtrem_negocios',
      'in_nav' => true,
      'model' => true,
      'icon' => 'fas fa-globe',
      'route' => 'temtrem-negocio',
      'fields' => [
        'id' => [
          'field' => 'id',
          'label' => 'ID',
          'input_type' => false,
          'input_bind' => false,
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => false,
        ],
        'user_id' => [
          'field' => 'user_id',
          'label' => 'User_id',
          'input_type' => 'ui-user',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => true,
        ],
        'name' => [
          'field' => 'name',
          'label' => 'Name',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'type' => [
          'field' => 'type',
          'label' => 'Type',
          'input_type' => 'ui-temtrem-negocio-type',
          'input_bind' => [],
          'input_options' => [
            'store' => 'Store',
            'service' => 'Service',
          ],
          'in_datatable' => true,
          'in_form' => true,
        ],
        'nomadic' => [
          'field' => 'nomadic',
          'label' => 'Nomadic',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => true,
        ],
        'nomadic_lat' => [
          'field' => 'nomadic_lat',
          'label' => 'Nomadic_lat',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'nomadic_lng' => [
          'field' => 'nomadic_lng',
          'label' => 'Nomadic_lng',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'content' => [
          'field' => 'content',
          'label' => 'Content',
          'input_type' => 'ui-text',
          'input_bind' => [
            'multiline' => 'true',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'lat' => [
          'field' => 'lat',
          'label' => 'Lat',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'lng' => [
          'field' => 'lng',
          'label' => 'Lng',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'route' => [
          'field' => 'route',
          'label' => 'Route',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'number' => [
          'field' => 'number',
          'label' => 'Number',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'complement' => [
          'field' => 'complement',
          'label' => 'Complement',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'zipcode' => [
          'field' => 'zipcode',
          'label' => 'Zipcode',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'district' => [
          'field' => 'district',
          'label' => 'District',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'city' => [
          'field' => 'city',
          'label' => 'City',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'state' => [
          'field' => 'state',
          'label' => 'State',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'st' => [
          'field' => 'st',
          'label' => 'St',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'country' => [
          'field' => 'country',
          'label' => 'Country',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'co' => [
          'field' => 'co',
          'label' => 'Co',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'created_at' => [
          'field' => 'created_at',
          'label' => 'Criado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'updated_at' => [
          'field' => 'updated_at',
          'label' => 'Alterado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'deleted_at' => [
          'field' => 'deleted_at',
          'label' => 'Deletado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
      ],
    ],
    'shop_orders' => [
      'pk' => 'id',
      'field_label' => 'id',
      'field_image' => false,
      'singular' => 'Shop_order',
      'plural' => 'Shop_orders',
      'in_nav' => true,
      'model' => true,
      'icon' => 'fas fa-globe',
      'route' => 'shop-order',
      'fields' => [
        'id' => [
          'field' => 'id',
          'label' => 'ID',
          'input_type' => false,
          'input_bind' => false,
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => false,
        ],
        'owner_id' => [
          'field' => 'owner_id',
          'label' => 'Owner_id',
          'input_type' => 'ui-user',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'buyer_id' => [
          'field' => 'buyer_id',
          'label' => 'Buyer_id',
          'input_type' => 'ui-user',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'status' => [
          'field' => 'status',
          'label' => 'Status',
          'input_type' => 'ui-shop-order-status',
          'input_bind' => [],
          'input_options' => [
            'em-andamento' => 'Em Andamento',
            'concluido' => 'Concluido',
          ],
          'in_datatable' => true,
          'in_form' => true,
        ],
        'created_at' => [
          'field' => 'created_at',
          'label' => 'Criado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'updated_at' => [
          'field' => 'updated_at',
          'label' => 'Alterado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'deleted_at' => [
          'field' => 'deleted_at',
          'label' => 'Deletado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
      ],
    ],
    'shop_orders_items' => [
      'pk' => 'id',
      'field_label' => 'id',
      'field_image' => false,
      'singular' => 'Shop_orders_item',
      'plural' => 'Shop_orders_items',
      'in_nav' => false,
      'model' => false,
      'icon' => 'fas fa-globe',
      'route' => 'shop-orders-item',
      'fields' => [
        'id' => [
          'field' => 'id',
          'label' => 'ID',
          'input_type' => false,
          'input_bind' => false,
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => false,
        ],
        'user_id' => [
          'field' => 'user_id',
          'label' => 'User_id',
          'input_type' => 'ui-user',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'product_id' => [
          'field' => 'product_id',
          'label' => 'Product_id',
          'input_type' => 'ui-shop-product',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'quantity' => [
          'field' => 'quantity',
          'label' => 'Quantity',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
      ],
    ],
    'shop_products' => [
      'pk' => 'id',
      'field_label' => 'name',
      'field_image' => false,
      'singular' => 'Shop_product',
      'plural' => 'Shop_products',
      'in_nav' => true,
      'model' => true,
      'icon' => 'fas fa-globe',
      'route' => 'shop-product',
      'fields' => [
        'id' => [
          'field' => 'id',
          'label' => 'ID',
          'input_type' => false,
          'input_bind' => false,
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => false,
        ],
        'store_id' => [
          'field' => 'store_id',
          'label' => 'Store_id',
          'input_type' => 'ui-shop-store',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'name' => [
          'field' => 'name',
          'label' => 'Name',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'price' => [
          'field' => 'price',
          'label' => 'Price',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'price_promo' => [
          'field' => 'price_promo',
          'label' => 'Price_promo',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'photos' => [
          'field' => 'photos',
          'label' => 'Photos',
          'input_type' => 'ui-text',
          'input_bind' => [
            'multiline' => 'true',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'created_at' => [
          'field' => 'created_at',
          'label' => 'Criado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'updated_at' => [
          'field' => 'updated_at',
          'label' => 'Alterado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'deleted_at' => [
          'field' => 'deleted_at',
          'label' => 'Deletado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
      ],
    ],
    'shop_products_comments' => [
      'pk' => 'id',
      'field_label' => 'id',
      'field_image' => false,
      'singular' => 'Shop_products_comment',
      'plural' => 'Shop_products_comments',
      'in_nav' => false,
      'model' => false,
      'icon' => 'fas fa-globe',
      'route' => 'shop-products-comment',
      'fields' => [
        'id' => [
          'field' => 'id',
          'label' => 'ID',
          'input_type' => false,
          'input_bind' => false,
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => false,
        ],
        'user_id' => [
          'field' => 'user_id',
          'label' => 'User_id',
          'input_type' => 'ui-user',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'product_id' => [
          'field' => 'product_id',
          'label' => 'Product_id',
          'input_type' => 'ui-shop-product',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'comment' => [
          'field' => 'comment',
          'label' => 'Comment',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'created_at' => [
          'field' => 'created_at',
          'label' => 'Criado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'updated_at' => [
          'field' => 'updated_at',
          'label' => 'Alterado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'deleted_at' => [
          'field' => 'deleted_at',
          'label' => 'Deletado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
      ],
    ],
    'shop_products_rates' => [
      'pk' => 'id',
      'field_label' => 'id',
      'field_image' => false,
      'singular' => 'Shop_products_rate',
      'plural' => 'Shop_products_rates',
      'in_nav' => false,
      'model' => false,
      'icon' => 'fas fa-globe',
      'route' => 'shop-products-rate',
      'fields' => [
        'id' => [
          'field' => 'id',
          'label' => 'ID',
          'input_type' => false,
          'input_bind' => false,
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => false,
        ],
        'user_id' => [
          'field' => 'user_id',
          'label' => 'User_id',
          'input_type' => 'ui-user',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'product_id' => [
          'field' => 'product_id',
          'label' => 'Product_id',
          'input_type' => 'ui-shop-product',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'vote' => [
          'field' => 'vote',
          'label' => 'Vote',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'created_at' => [
          'field' => 'created_at',
          'label' => 'Criado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'updated_at' => [
          'field' => 'updated_at',
          'label' => 'Alterado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'deleted_at' => [
          'field' => 'deleted_at',
          'label' => 'Deletado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
      ],
    ],
    'shop_promos' => [
      'pk' => 'id',
      'field_label' => 'name',
      'field_image' => false,
      'singular' => 'Shop_promo',
      'plural' => 'Shop_promos',
      'in_nav' => true,
      'model' => true,
      'icon' => 'fas fa-globe',
      'route' => 'shop-promo',
      'fields' => [
        'id' => [
          'field' => 'id',
          'label' => 'ID',
          'input_type' => false,
          'input_bind' => false,
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => false,
        ],
        'store_id' => [
          'field' => 'store_id',
          'label' => 'Store_id',
          'input_type' => 'ui-shop-store',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'name' => [
          'field' => 'name',
          'label' => 'Name',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'discount' => [
          'field' => 'discount',
          'label' => 'Discount',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'date_start' => [
          'field' => 'date_start',
          'label' => 'Date_start',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'date_final' => [
          'field' => 'date_final',
          'label' => 'Date_final',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'created_at' => [
          'field' => 'created_at',
          'label' => 'Criado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'updated_at' => [
          'field' => 'updated_at',
          'label' => 'Alterado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'deleted_at' => [
          'field' => 'deleted_at',
          'label' => 'Deletado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
      ],
    ],
    'shop_stores' => [
      'pk' => 'id',
      'field_label' => 'name',
      'field_image' => false,
      'singular' => 'Shop_store',
      'plural' => 'Shop_stores',
      'in_nav' => true,
      'model' => true,
      'icon' => 'fas fa-globe',
      'route' => 'shop-store',
      'fields' => [
        'id' => [
          'field' => 'id',
          'label' => 'ID',
          'input_type' => false,
          'input_bind' => false,
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => false,
        ],
        'owner_id' => [
          'field' => 'owner_id',
          'label' => 'Owner_id',
          'input_type' => 'ui-user',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'name' => [
          'field' => 'name',
          'label' => 'Name',
          'input_type' => 'ui-text',
          'input_bind' => [
            'class' => 'form-control',
          ],
          'input_options' => false,
          'in_datatable' => true,
          'in_form' => true,
        ],
        'created_at' => [
          'field' => 'created_at',
          'label' => 'Criado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'updated_at' => [
          'field' => 'updated_at',
          'label' => 'Alterado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
        'deleted_at' => [
          'field' => 'deleted_at',
          'label' => 'Deletado em',
          'input_type' => 'ui-datetime',
          'input_bind' => [],
          'input_options' => false,
          'in_datatable' => false,
          'in_form' => false,
        ],
      ],
    ],
  ],
];